plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'java-library'
	id 'maven-publish'
}

group = 'com.example'
version = '0.0.4-SNAPSHOT'
description = 'java-shared'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	withSourcesJar()
	withJavadocJar()
}

repositories {
	mavenCentral()
	mavenLocal()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'

	// OpenTelemetryを利用するために追加
	implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
	implementation 'am.ik.spring.opentelemetry:otel-logs-autoconfigure:0.6.0'

	compileOnly 'org.projectlombok:lombok'
	//developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	//testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	//testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}

bootJar {
	enabled = false
}

jar {
	enabled = true
}

publishing {
	publications {
		maven(MavenPublication) {
			groupId = "${project.group}"
			artifactId = "${project.name}"
			version = "${project.version}"
			from components.java

			// dependency-managementで依存のversion解決をさせたい場合は必須
			versionMapping {
				usage('java-api') {
					fromResolutionOf('runtimeClasspath')
				}
				usage('java-runtime') {
					fromResolutionResult()
				}
			}
		}
	}
}

tasks.withType(Javadoc) {
	// JavaDocタスク実行時にデフォルトコンストラクタの記述がないクラスで警告が出るのを抑止するため
	// DocLintのmissingグループを抑止する
	// 【参考】
	// https://stackoverflow.com/questions/77569272/how-to-suppress-javadoc-warnings-in-gradle-build
	// https://stackoverflow.com/questions/34874175/disable-all-javadoc-in-gradle/36939917#36939917
	// https://docs.oracle.com/javase/jp/18/docs/specs/man/javadoc.html#groups
	options.addBooleanOption('Xdoclint:all,-missing', true)
}
