plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'java-library'
	id 'maven-publish'
}

group = 'com.example'
version = '0.0.2-SNAPSHOT'
description = 'java-shared'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
    withSourcesJar()
    withJavadocJar()
}

repositories {
	mavenCentral()
	mavenLocal()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'

	// OpenTelemetryを利用するために追加
	implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
	implementation 'am.ik.spring.opentelemetry:otel-logs-autoconfigure:0.6.0'

	compileOnly 'org.projectlombok:lombok'
	//developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	//testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	//testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "${project.group}"
            artifactId = "${project.name}"
            version = "${project.version}"
            from components.java

			// dependency-managementで依存のversion解決をさせたい場合は必須
			versionMapping {
				usage('java-api') {
					fromResolutionOf('runtimeClasspath')
				}
				usage('java-runtime') {
					fromResolutionResult()
				}
			}
        }
    }
}
