#-----------------------------------------------------------------------------------------------------------------------
# オブザーバビリティ設定
#-----------------------------------------------------------------------------------------------------------------------

# インスタンスIDの設定
# インスタンスIDはマイクロサービスなどで同じサービスを複数のインスタンス（ホスト）で起動する際に識別するためのIDです。
# 特に可視化する際に必要となるため、環境変数の HOSTNAME を指定し、デフォルトでは開発用の local-dev を指定しています。
management.opentelemetry.resource-attributes.service.instance.id=${HOSTNAME:local-dev}

# OTLPサーバー（メトリクス）のURL
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

# トレースの何割を収集するかという設定。1.0が100%
management.tracing.sampling.probability=1.0

# OTelコレクター（トレース）のHTTP APIへのURL
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

# OTelコレクター（ログ）のHTTP APIへのURL
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

# logback-appender の追加設定（意味は不明、無くても問題ない？）
management.opentelemetry.instrumentation.logback-appender.capture-experimental-attributes=true
management.opentelemetry.instrumentation.logback-appender.capture-key-value-pair-attributes=true

#-----------------------------------------------------------------------------------------------------------------------
# サービス設定
#-----------------------------------------------------------------------------------------------------------------------

sandbox.service.url.config.map.sandbox-service=http://localhost:18081
sandbox.service.url.config.map.sandbox-2nd-service=http://localhost:18082
